config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
    member do
      get "invite/:token", to: "groups#group_invite", as: "invite"
      put :generate_token
    end
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  # Logix web pages resources
  root "logix#index"
  get  "/examples", to: "logix#examples"
  get  "/tos", to: "logix#tos"
  get  "/teachers", to: "logix#teachers"
  get  "/contribute", to: "logix#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  notify_to :users, controller: "users/notifications"

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/logix#edit", as: "profile_edit"
    patch "/:id/update", to: "users/logix#update", as: "profile_update"
    get "/:id/groups", to: "users/logix#groups", as: "user_groups"
    get "/:id/", to: "users/logix#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/logix#typeahead_educational_institute"
    get "/:id/notifications", to: "users/notifications#index", as: "notifications"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    get "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  # lti
  scope "lti"  do
    match 'launch', to: 'lti#launch', via: [:get, :post] 
  end

  mount Commontator::Engine => "/commontator"

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    get "get_data/:id", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/simulator_old" do
    get "/:id", to: "simulator_old#show", as: "simulator_old"
    get "/edit/:id", to: "simulator_old#edit", as: "simulator_old_edit"
    post "/get_data", to: "simulator_old#get_data"
    post "/post_issue", to: "simulator_old#post_issue"
    post "/update_data", to: "simulator_old#update"
    post "/update_image", to: "simulator_old#update_image"
    post "/create_data", to: "simulator_old#create"
    post "/verilogcv", to: "simulator_old#verilog_cv"
    get "/", to: "simulator_old#new", as: "simulator_old_new"
    get "/embed/:id", to: "simulator_old#embed"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index new]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/zt-p6bgler9-~8vWvsKmL9lZeYg4pP9hwQ"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      resources :projects, only: %i[index show update destroy] do
        member do
          get "toggle-star", to: "projects#toggle_star"
          get "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/mentored", to: "groups#groups_mentored"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_secure_token :group_token
  validates :name, length: { minimum: 1 }
  belongs_to :mentor, class_name: "User"
  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members

  has_many :assignments, dependent: :destroy
  has_many :pending_invitations, dependent: :destroy

  after_commit :send_creation_mail, on: :create
  scope :with_valid_token, -> { where("token_expires_at >= ?", Time.zone.now) }
  TOKEN_DURATION = 12.days

  def send_creation_mail
    GroupMailer.new_group_email(mentor, self).deliver_later
  end

  def has_valid_token?
    token_expires_at.present? && token_expires_at > Time.zone.now
  end

  def reset_group_token
    transaction do
      regenerate_group_token
      update(token_expires_at: Time.zone.now + TOKEN_DURATION)
    end
  end
end

app/controllers/api/v1/groups_controller.rb
# frozen_string_literal: true

class Api::V1::GroupsController < Api::V1::BaseController
  before_action :authenticate_user!
  before_action :set_group, except: %i[index groups_mentored create]
  before_action :set_options, only: %i[index groups_mentored create show update]
  before_action :check_show_access, only: [:show]
  before_action :check_edit_access, only: %i[update destroy]

  WHITELISTED_INCLUDE_ATTRIBUTES = %i[group_members assignments].freeze

  # GET /api/v1/groups
  def index
    @groups = paginate(current_user.groups)
    @options[:links] = link_attrs(@groups, api_v1_groups_url)
    render json: Api::V1::GroupSerializer.new(@groups, @options)
  end

  # GET /api/v1/groups/mentored
  def groups_mentored
    @groups = paginate(current_user.groups_mentored)
    @options[:links] = link_attrs(@groups, api_v1_groups_mentored_url)
    render json: Api::V1::GroupSerializer.new(@groups, @options)
  end

  # POST /api/v1/groups/
  def create
    @group = current_user.groups_mentored.new(group_params)
    @group.save!
    if @group.save
      render json: Api::V1::GroupSerializer.new(@group, @options), status: :created
    else
      invalid_resource!(@group.errors)
    end
  end

  # GET /api/v1/groups/:id
  def show
    render json: Api::V1::GroupSerializer.new(@group, @options)
  end

  # PATCH /api/v1/groups/:id
  def update
    @group.update!(group_params)
    if @group.update(group_params)
      render json: Api::V1::GroupSerializer.new(@group), status: :accepted
    else
      invalid_resource!(@group.errors)
    end
  end

  # DELETE /api/v1/groups/:id
  def destroy
    @group.destroy!
    render json: {}, status: :no_content
  end

  private

    # include=group_members,assignments
    def include_resource
      params[:include].split(",")
                      .map { |resource| resource.strip.to_sym }
                      .select { |resource| WHITELISTED_INCLUDE_ATTRIBUTES.include?(resource) }
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def set_options
      @options = {}
      @options[:include] = include_resource if params.key?(:include)
      @options[:params] = { current_user: current_user }
    end

    def group_params
      params.require(:group).permit(:name, :mentor_id)
    end

    def check_show_access
      authorize @group, :show_access?
    end

    def check_edit_access
      authorize @group, :admin_access?
    end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy group_invite generate_token]
  before_action :authenticate_user!
  before_action :check_show_access, only: %i[show edit update destroy]
  before_action :check_edit_access, only: %i[edit update destroy generate_token]

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_member = @group.group_members.new
    @group.assignments.each do |assignment|
      if (assignment.status == "reopening") && (assignment.deadline < Time.zone.now)
        assignment.status = "closed"
        assignment.save
      end
    end
  end

  def generate_token
    @group = Group.find(params[:id])
    @group.reset_group_token unless @group.has_valid_token?
  end

  def group_invite
    if Group.with_valid_token.exists?(group_token: params[:token])
      if current_user.groups.exists?(id: @group)
        notice = "Member is already present in the group."
      else
        current_user.group_members.create!(group: @group)
        notice = "Group member was successfully added."
      end
    elsif Group.exists?(group_token: params[:token])
      notice = "Url is expired, request a new one from owner of the group."
    else
      notice = "Invalid url"
    end
    redirect_to group_path(@group), notice: notice
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups_mentored.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path(current_user), notice: "Group was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :mentor_id)
    end

    def check_show_access
      authorize @group, :show_access?
    end

    def check_edit_access
      authorize @group, :admin_access?
    end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_add_member_modal.html.erb
<div id="addmemberModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("add_members") %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.add_member_description") %></p>
        <%= form_with(model: group_member, local: true) do |form| %>
          <% if group_member.errors.any? %>
            <div id="error-message">
              <ul>
                <% group_member.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.hidden_field :group_id, id: :group_member_group_id %>
          </div>
          <div class="form-group">
            <%= form.label :emails %>
            <%= form.text_area :emails, id: :group_member_emails, rows: 4, class: 'form-control form-input', autofocus: true %>
          </div>
          <div class="modal-footer">
            <%= form.submit  class: 'btn primary-button' %>
          </div>
        <% end %>
      </div>
      <div class="mx-auto text-center p-3">
        <p><%= t("groups.use_alternative") %></p>
        <%= button_to generate_token_group_path,{remote: true,method: :put,class: 'btn primary-button', 'data-toggle':'collapse', 'href':'#collapseExample', 'aria-expanded':'false', 'aria-controls':'collapseExample'} do %>
          <i class="fas fa-external-link-alt"></i>
          <span><%= t("groups.invite_link_btn") %></span>
        <% end %>
        <div class="collapse" id="collapseExample">
          <textarea readonly="readonly" id="embedInviteLink" class="group-invite-link-text" rows="4" cols="35"></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_delete_assignment_confirmation_modal.html.erb
<div id="deleteassignmentModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.remove_assignment_message") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to '#', method: :delete, class: "btn primary-delete-button", id: "groups-assignment-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_delete_member_confirmation_modal.html.erb
<div id="deletememberModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.remove_member_message") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to '#', method: :delete, class: "btn primary-delete-button", id: "groups-member-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div class="error-message">
      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-3 groups-form-text-container">
    <div class="field form-group">
      <h5><%= form.label :name %></h5>
      <div class="input-group groups-input-group">
        <%= form.text_field :name, id: :group_name, class: 'form-control form-input', autofocus: true %>
      </div>
    </div>
  </div>
  <div class="groups-form-text-container">
    <%= form.submit class: 'btn primary-button groups-form-primary-button' %>
    <%= link_to t("back"), :back, class: 'groups-form-anchor-text anchor-text' %>
  </div>
<% end %>

app/views/groups/_group_members.html.erb
<% group.users.each do |user| %>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 groups-members-card-container">
    <div class="groups-members-card">
      <div class="row">
        <div class="col-7 groups-members-card-details">
          <i class="fa fa-user"></i>
          <div class="groups-members-card-name-container">
            <%= link_to user.name, user, class: "groups-members-card-name" %>
          </div>
          <% if policy(group).admin_access? %>
            <p class="groups-members-card-email"><%= user.email %></p>
          <% end %>
        </div>
        <div class="col-5 groups-members-card-button">
          <% if policy(group).admin_access? %>
            <%= link_to '#', data: {toggle: "modal", target: "#deletememberModal", currentgroupmember: GroupMember.find_by(user_id:user.id,group_id:group.id).id}, class:"mini-button groups-delete-mini-button" do %>
              <%= image_tag("SVGs/deleteGroup.svg", alt: "Remove Member") %>
              <span><%= t("remove") %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_lms_credentials_modal.html.erb
<div id="lmscredentialsModal-<%= assignment.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= assignment.name %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <h5>LMS Credentials</h5>
        <br>
        <div class="groups-lms-modal">
          <strong>Tool Url:</strong>
          <p id="toolurl" class="link-text"><%= URI.join request.original_url, '/lti/launch' %></p>
          <a class="btn primary-button groups-copy-lms-credentials-button" onclick="return copyToClipboard('#toolurl');">
            <%= image_tag("SVGs/createCopy.svg", alt: "Create Copy") %>
          </a>
        </div>
        <div class="groups-lms-modal">
          <strong>Consumer Key:</strong>
          <p id="consumerkey-<%= assignment.id %>" class="link-text"><%= assignment.lti_consumer_key %></p>
          <a class="btn primary-button groups-copy-lms-credentials-button" onclick="return copyToClipboard('#consumerkey-<%= assignment.id %>');">
            <%= image_tag("SVGs/createCopy.svg", alt: "Create Copy") %>
          </a>
        </div>
        <div class="groups-lms-modal">
          <strong>Shared Secret:</strong>
          <p id="sharedsecret-<%= assignment.id %>" class="link-text"><%= assignment.lti_shared_secret %></p>
          <a class="btn primary-button groups-copy-lms-credentials-button" onclick="return copyToClipboard('#sharedsecret-<%= assignment.id %>');">
            <%= image_tag("SVGs/createCopy.svg", alt: "Create Copy") %>
          </a>
        </div>
        <br>
        <div>
          <a href=<%= lms_integration_tutorial %> target="_blank">Learn how to integrate CircuitVerse assignments with any LMS</a>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  function copyToClipboard(element) {
    setTimeout(function(){
      var $temp = $("<input>");
      $("body").append($temp);
      $temp.val($(element).text()).select();
      document.execCommand("copy");
      $temp.remove();
    },100);
  }
</script>

app/views/groups/edit.html.erb
<% content_for :title, t("groups.edit.title", name: @group.name) %>
<div class="container">
  <div class="row center-row">
    <div class="col-xs col-sm col-md col-lg">
      <h2 class="submain-heading"><%= t("groups.edit.main_heading") %></h2>
    </div>
  </div>
  <div class="row center-row">
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-6">
      <%= image_tag "PNGs/editGroupName.png", alt: "Group Sketch", :class => "groups-center-image center-image" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-6">
      <div class="container">
        <div class="center-row groups-background-card">
          <%= render 'form', group: @group %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/generate_token.js.erb
$("#embedInviteLink").html("<%= group_url(@group) %>/invite/<%= @group.group_token %> ");

app/views/groups/new.html.erb
<% content_for :title, t("groups.new.title") %>
<div class="container">
  <div class="row center-row">
    <div class="col-xs col-sm col-md col-lg">
      <h2 class="submain-heading"><%= t("groups.new.main_heading") %></h2>
      <p class="main-description"><%= t("groups.new.main_description_html") %></p>
    </div>
  </div>
  <div class="row center-row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-6">
      <div class="container">
        <div class="center-row groups-background-card">
          <%= render 'form', group: @group %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-6">
      <%= image_tag "PNGs/newGroup.png", alt: "New Group Sketch", :class => "groups-center-image center-image" %>
    </div>
  </div>
</div>