config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
    member do
      get "invite/:token", to: "groups#group_invite", as: "invite"
      put :generate_token
    end
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  # Logix web pages resources
  root "logix#index"
  get  "/examples", to: "logix#examples"
  get  "/tos", to: "logix#tos"
  get  "/teachers", to: "logix#teachers"
  get  "/contribute", to: "logix#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  notify_to :users, controller: "users/notifications"

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/logix#edit", as: "profile_edit"
    patch "/:id/update", to: "users/logix#update", as: "profile_update"
    get "/:id/groups", to: "users/logix#groups", as: "user_groups"
    get "/:id/", to: "users/logix#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/logix#typeahead_educational_institute"
    get "/:id/notifications", to: "users/notifications#index", as: "notifications"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    get "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  # lti
  scope "lti"  do
    match 'launch', to: 'lti#launch', via: [:get, :post] 
  end

  mount Commontator::Engine => "/commontator"

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    get "get_data/:id", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/simulator_old" do
    get "/:id", to: "simulator_old#show", as: "simulator_old"
    get "/edit/:id", to: "simulator_old#edit", as: "simulator_old_edit"
    post "/get_data", to: "simulator_old#get_data"
    post "/post_issue", to: "simulator_old#post_issue"
    post "/update_data", to: "simulator_old#update"
    post "/update_image", to: "simulator_old#update_image"
    post "/create_data", to: "simulator_old#create"
    post "/verilogcv", to: "simulator_old#verilog_cv"
    get "/", to: "simulator_old#new", as: "simulator_old_new"
    get "/embed/:id", to: "simulator_old#embed"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index new]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/zt-p6bgler9-~8vWvsKmL9lZeYg4pP9hwQ"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      resources :projects, only: %i[index show update destroy] do
        member do
          get "toggle-star", to: "projects#toggle_star"
          get "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/mentored", to: "groups#groups_mentored"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  before_action :set_user, only: %i[show update]
  before_action :authenticate_user!
  before_action :check_access, only: [:update]
  before_action :set_details_access, except: %i[index me]

  # GET api/v1/users
  def index
    @users = paginate(User.all)
    @options = { params: { only_name: true } }
    @options[:links] = link_attrs(@users, api_v1_users_url)
    render json: Api::V1::UserSerializer.new(@users, @options)
  end

  # GET api/v1/users/:id
  def show
    render json: Api::V1::UserSerializer.new(@user, @options)
  end

  # GET api/v1/me
  def me
    @options = { params: { has_details_access: true } }
    render json: Api::V1::UserSerializer.new(current_user, @options)
  end

  # PATCH api/v1/users/:id
  def update
    @user.update!(user_params)
    if @user.update(user_params)
      render json: Api::V1::UserSerializer.new(@user, @options), status: :accepted
    else
      invalid_resource!(@user.errors)
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def check_access
      authorize @user, :edit?
    end

    def set_details_access
      @options = { params: { has_details_access: @user.eql?(current_user) } }
    end

    def user_params
      params.permit(:name, :locale, :educational_institute, :country, :subscribed)
    end
end

app/controllers/logix_controller.rb
# frozen_string_literal: true

class LogixController < ApplicationController
  MAXIMUM_FEATURED_CIRCUITS = 3

  def index
    @projects = Project.select(:id, :author_id, :image_preview, :name, :slug)
                       .public_and_not_forked
                       .where.not(image_preview: "default.png")
                       .order(id: :desc)
                       .includes(:author)
                       .limit(Project.per_page)

    page = params[:page].to_i
    @projects = if page.positive?
      @projects.paginate(page: page)
    else
      @projects.paginate(page: nil)
    end

    @featured_circuits = Project.joins(:featured_circuit)
                                .order("featured_circuits.created_at DESC")
                                .includes(:author)
                                .limit(MAXIMUM_FEATURED_CIRCUITS)

    respond_to do |format|
      format.html
      format.json { render json: @projects }
      format.js
    end
  end

  def examples
    @examples = [{ name: "Full Adder from 2-Half Adders", id: "users/3/projects/247",
                   img: "examples/fullAdder_n.jpg" },
                 { name: "16 Bit ripple carry adder", id: "users/3/projects/248",
                   img: "examples/RippleCarry_n.jpg" },
                 { name: "Asynchronous Counter", id: "users/3/projects/249",
                   img: "examples/AsyncCounter_n.jpg" },
                 { name: "Keyboard", id: "users/3/projects/250",
                   img: "examples/Keyboard_n.jpg" },
                 { name: "FlipFlop", id: "users/3/projects/251",
                   img: "examples/FlipFlop_n.jpg" },
                 { name: "ALU 74LS181 by Ananth Shreekumar", id: "users/126/projects/252",
                   img: "examples/ALU_n.jpg" }]
  end

  def tos; end

  def teachers; end

  def contribute; end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/logix_controller.rb
# frozen_string_literal: true

class Users::LogixController < ApplicationController
  TYPEAHEAD_INSTITUTE_LIMIT = 50

  include UsersLogixHelper

  before_action :authenticate_user!, only: %i[edit update groups]
  before_action :set_user, except: [:typeahead_educational_institute]

  def index
    @profile = ProfileDecorator.new(@user)
    @projects = @user.rated_projects
  end

  def edit; end

  def typeahead_educational_institute
    query = params[:query]
    institute_list = User.where("educational_institute LIKE :query", query: "%#{query}%")
                         .distinct
                         .limit(TYPEAHEAD_INSTITUTE_LIMIT)
                         .pluck(:educational_institute)
    typeahead_array = institute_list.map { |item| { name: item } }
    render json: typeahead_array
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_projects_path(current_user)
    else
      render :edit
    end
  end

  def groups
    @user = authorize @user
    @groups_mentored = Group.where(id: Group.joins(:mentor).where(mentor: @user))
                            .select("groups.*, COUNT(group_members.id) as group_member_count")
                            .joins("left outer join group_members on \
                              (group_members.group_id = groups.id)")
                            .group("groups.id")
  end

  private

    def profile_params
      params.require(:user).permit(:name, :profile_picture, :country, :educational_institute,
                                   :subscribed, :locale)
    end

    def set_user
      @profile = current_user
      @user = User.find(params[:id])
    end
end

app/controllers/users/notifications_controller.rb
# frozen_string_literal: true

class Users::NotificationsController < ActivityNotification::NotificationsController
  before_action :authenticate_user!
  # GET /:target_type/:target_id/notifications
  # def index
  #   super
  # end

  # POST /:target_type/:target_id/notifications/open_all
  # def open_all
  #   super
  # end

  # GET /:target_type/:target_id/notifications/:id
  # def show
  #   super
  # end

  # DELETE /:target_type/:target_id/notifications/:id
  # def destroy
  #   super
  # end

  # POST /:target_type/:target_id/notifications/:id/open
  # def open
  #   super
  # end

  # GET /:target_type/:target_id/notifications/:id/move
  # def move
  #   super
  # end

  # No action routing
  # This method needs to be public since it is called from view helper
  # def target_view_path
  #   super
  # end

  protected

    def set_target
      super
      raise ApplicationPolicy::CustomAuthException, "Wrong user" if @target != current_user
    end

  # def set_notification
  #   super
  # end

  # def set_index_options
  #   super
  # end

  # def load_index
  #   super
  # end

  # def controller_path
  #   super
  # end

  # def set_view_prefixes
  #   super
  # end

  # def return_back_or_ajax
  #   super
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    generic_callback("facebook")
  end

  def google_oauth2
    generic_callback("google")
  end

  def github
    generic_callback("github")
  end

  def microsoft_office365
    generic_callback("microsoft_office365")
  end

  def generic_callback(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except(:extra).except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/logix/_dashboard.html.erb
<% projects.each do |project| %>
  <% if policy(project).check_direct_view_access? %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 users-circuits-column circuit-card-js">
      <div class="card text-center users-card">
        <div class="card-header users-card-header">
          <div class="users-card-name">
            <p><%= project.name %></p>
            <span class="tooltiptext"><%= project.name %></span>
          </div>
          <div class="users-tag-container">
            <% if !project.assignment_id.nil? %>
              <span class="badge search-tag"><%= t("assignment") %></span>
            <% end %>
              <span class="badge search-tag"><%= project.project_access_type %></span>
          </div>
        </div>
        <div class="card-body users-card-body">
          <img class="users-card-image" src="<%= project.image_preview.url %>" alt="<%= project.name %>">
        </div>
        <div class="card-footer users-card-footer">
          <% if policy(project).user_access? %>
            <a href="<%= simulator_edit_path(project) %>" class="btn primary-button" target="_blank"><%= t("launch") %></a>
          <% else %>
            <a href="<%= create_fork_project_path(project) %>" class="btn primary-button" target="_blank"><%= t("fork") %></a>
          <% end %>
            <%= link_to t("view"), '#', class: "previewButton btn primary-button", data: {toggle: "modal", target: "#projectModal", currentproject: project} %>
            <a href="<%= user_project_path(project.author_id, project) %>" class="btn primary-button" target="_blank"><%= t("more") %></a>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

app/views/users/logix/_delete_group_confirmation_modal.html.erb
<div id="deletegroupModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><%= t("users.logix.delete_group_confirmation") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to '#', method: :delete, class: "btn primary-delete-button", id: "groups-group-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/logix/_delete_user_confirmation_modal.html.erb
<div id="deleteuserModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><%= t("users.logix.delete_user_confirmation") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to '#', method: :delete, class: "btn primary-delete-button", id: "users-user-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/logix/_view_project_modal.html.erb
<div id="projectModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog ">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("users.logix.preview_project") %></h4>
        <button type="button" class="close close-modal" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-4by3 feature feature-preview users-iframe-container">
          <iframe src="" id="projectPreview" scrolling="no" webkitAllowFullScreen mozAllowFullScreen allowFullScreen> </iframe>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to t("fork"), '#', class: "btn primary-button", id: "project-fork-button" %>
        <%= link_to t("more"), '#', class: "btn primary-button", id: "project-more-button", target: "_blank" %>
      </div>
    </div>
  </div>
</div>

app/views/users/logix/groups.html.erb
<% if @user.name %>
  <% content_for :title, t("users.logix.groups.title", name: @user.name) %>
<% else %>
  <% content_for :title, t("users.logix.groups.alt_title") %>
<% end %>


<div class="container">
  <% if notice %>
  <div class="row" id='alertdiv'>
    <div class="alert alert-success alert-dismissible container text-center">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h6><%= notice %></h6>
    </div>
  </div>
  <% end %>
  <div class="row center-row">
    <div class="col-xs col-sm col-md col-lg">
      <h1 class="submain-heading"><%= t("users.logix.groups.main_heading") %></h1>
      <%= link_to t("users.logix.groups.make_new_group"), new_group_path, class: "btn primary-button groups-add-primary-button" %>
    </div>
  </div>
  <br>
  <% if @groups_mentored.present? %>
    <h4 class="submain-heading"><%= t("users.logix.groups.groups_user_mentor_to") %></h4>
    <div class="row center-row">
      <% @groups_mentored.each do |group| %>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="groups-card groups-mentor-card">
            <div class="groups-mentor-card-name"><%= group.name %></div>
            <div>
              <p><%= t("users.logix.groups.total_members",group_member_count: group.group_member_count ) %> </p>
            </div>
            <div class="groups-mentor-card-mini-buttons">
              <%= link_to group, class: "mini-button groups-mentor-card-view-mini-button" do %>
                <%= image_tag("SVGs/viewGroup.svg", alt: "View Group") %>
                <span><%= t("view") %></span>
              <% end %>
              <%= link_to edit_group_path(group), class: "mini-button groups-mentor-card-edit-mini-button" do %>
                <%= image_tag("SVGs/editGroup.svg", alt: "Edit Group") %>
                <span><%= t("edit") %></span>
              <% end %>
              <%= link_to '#', class: "mini-button groups-mentor-card-delete-mini-button", data: {toggle: "modal", target: "#deletegroupModal", currentgroup: group.id} do %>
                <%= image_tag("SVGs/deleteGroup.svg", alt: "Delete Group") %>
                <span><%= t("delete") %></span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>
  <% if @user.groups.count!=0 %>
    <h4 class="submain-heading"><%= t("users.logix.groups.groups_user_belong_to") %></h4>
    <div class="row center-row">
      <% @user.groups.each do |group| %>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
          <div class="groups-card groups-member-card">
            <div class="groups-member-card-details">
              <div class="groups-mentor-card-name groups-member-card-name"><%= group.name %></div>
              <p><%= t("users.logix.groups.total_members", group_member_count: group.group_members.count) %></p>
            </div>
            <div class="groups-mentor-card-buttons">
              <%= link_to group, class: "mini-button groups-mentor-card-view-mini-button groups-member-card-button" do %>
                <%= image_tag("SVGs/viewGroup.svg", alt: "View Group") %>
                <span><%= t("view") %></span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= render partial: "delete_group_confirmation_modal" %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#deletegroupModal").on("show.bs.modal", function(e) {
        let group = $(e.relatedTarget).data('currentgroup');
        $(e.currentTarget).find('#groups-group-delete-button').attr("href",
        "/groups/" + group.toString());
    });
  });
</script>

app/views/users/logix/search.html.erb
<% if @results.empty? %>
  <div class="container search-no-results-container">
    <div class="row center-row">
      <div class="col-12">
        <div class="search-no-results-image">
          <%= image_tag "SVGs/noResult.svg", alt: "No result image" %>
          <h6><%= t("users.logix.search.no_results") %></h6>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container search-container">
    <% @results.map { |user| ProfileDecorator.new(user) }.each do |profile| %>
      <div class="row center-row search-user-container">
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
          <div class="row center-row">
            <%= image_tag profile.profile_picture.url(:medium), alt: "project.name", class: "center-row search-usersearch-image" %>
            <p class=" center-row search-username"><%= profile.name %></p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 search-userdetails-container">
          <p class="search-user-details-text"><%= t("users.logix.member_since_html", member_since: profile.member_since) %></p>
          <p class="search-user-details-text"><%= t("users.logix.educational_institutes_html",educational_institute: profile.educational_institute) %></p>
          <p class="search-user-details-text"><%= t("users.logix.country_html", country_name: profile.country_name) %></p>
          <p class="search-user-details-text"><%= t("users.logix.total_circuits_made_html", total_circuits: profile.total_circuits) %></p>
          <a class="btn primary-button search-user-primary-button" target="_blank" href="<%= user_path(profile) %>"><%= t("view") %></a>
        </div>
      </div>
      <hr class="search-horizontal-rule">
    <% end %>
    <% unless @results.empty? %>
      <%= will_paginate(@results, renderer: SearchPaginateRenderer) %>
    <% end %>
  </div>
<% end %>